ci(matrix): use Android

diff --git a/.github/workflows/scan_with_matrix.yaml b/.github/workflows/scan_with_matrix.yaml
--- a/.github/workflows/scan_with_matrix.yaml
+++ b/.github/workflows/scan_with_matrix.yaml
@@ -112,48 +112,48 @@ jobs:
       # - name: Mount the device's Developer Disk Image
       #TODO: Uncomment this step after Appium Runner is stable to reduce rate limiting failures
       #   run: pymobiledevice3 mounter auto-mount
-      - name: Install Appium runner and check connection
-        continue-on-error: true
-        env:
-          CORELLIUM_API_ENDPOINT: ${{ secrets.CORELLIUM_API_ENDPOINT }}
-          CORELLIUM_API_TOKEN: ${{ secrets.CORELLIUM_API_TOKEN }}
-          APPIUM_DEFUALT_PORT: 8100
-          APPIUM_RUNNER_LAUNCH_RETRIES: 5
-          APPIUM_RUNNER_CURL_RETRIES: 60
-        timeout-minutes: 10
-        run: |
-          set -eu && source ./src/functions.sh
-          install_appium_runner_ios "${{ env.MATRIX_INSTANCE_ID }}"
-          matrix_instance_services_ip="$(get_instance_services_ip "${{ env.MATRIX_INSTANCE_ID }}")"
-          readonly APPIUM_TEST_URL="http://${matrix_instance_services_ip}:${APPIUM_DEFUALT_PORT}/status"
-          appium_runner_success='false'
-          for launch_attempt in $(seq 1 "${APPIUM_RUNNER_LAUNCH_RETRIES}"); do
-            if ! launch_appium_runner_ios "${{ env.MATRIX_INSTANCE_ID }}"; then
-              log_warning "Failed to launch app during attempt ${launch_attempt}"
-              continue
-            fi
-            for curl_attempt in $(seq 1 "${APPIUM_RUNNER_CURL_RETRIES}"); do
-              if curl --silent "${APPIUM_TEST_URL}" 2>/dev/null; then
-                appium_runner_success='true'
-                printf 'Appium runner comms succeeded on launch %s and curl attempt %s' \
-                  "${launch_attempt}" \
-                  "${curl_attempt}"
-                break 2
-              fi
-              sleep 0.1
-            done
-          done
-          if [ "${appium_runner_success}" != 'true' ]; then
-            log_error 'Failed to establish comms with Appium runner app'
-            exit 1
-          fi
+      # - name: Install Appium runner and check connection
+      #   continue-on-error: true
+      #   env:
+      #     CORELLIUM_API_ENDPOINT: ${{ secrets.CORELLIUM_API_ENDPOINT }}
+      #     CORELLIUM_API_TOKEN: ${{ secrets.CORELLIUM_API_TOKEN }}
+      #     APPIUM_DEFUALT_PORT: 8100
+      #     APPIUM_RUNNER_LAUNCH_RETRIES: 5
+      #     APPIUM_RUNNER_CURL_RETRIES: 60
+      #   timeout-minutes: 10
+      #   run: |
+      #     set -eu && source ./src/functions.sh
+      #     install_appium_runner_ios "${{ env.MATRIX_INSTANCE_ID }}"
+      #     matrix_instance_services_ip="$(get_instance_services_ip "${{ env.MATRIX_INSTANCE_ID }}")"
+      #     readonly APPIUM_TEST_URL="http://${matrix_instance_services_ip}:${APPIUM_DEFUALT_PORT}/status"
+      #     appium_runner_success='false'
+      #     for launch_attempt in $(seq 1 "${APPIUM_RUNNER_LAUNCH_RETRIES}"); do
+      #       if ! launch_appium_runner_ios "${{ env.MATRIX_INSTANCE_ID }}"; then
+      #         log_warning "Failed to launch app during attempt ${launch_attempt}"
+      #         continue
+      #       fi
+      #       for curl_attempt in $(seq 1 "${APPIUM_RUNNER_CURL_RETRIES}"); do
+      #         if curl --silent "${APPIUM_TEST_URL}" 2>/dev/null; then
+      #           appium_runner_success='true'
+      #           printf 'Appium runner comms succeeded on launch %s and curl attempt %s' \
+      #             "${launch_attempt}" \
+      #             "${curl_attempt}"
+      #           break 2
+      #         fi
+      #         sleep 0.1
+      #       done
+      #     done
+      #     if [ "${appium_runner_success}" != 'true' ]; then
+      #       log_error 'Failed to establish comms with Appium runner app'
+      #       exit 1
+      #     fi
       - name: Install Corellium Cafe from URL
         env:
           CORELLIUM_API_ENDPOINT: ${{ secrets.CORELLIUM_API_ENDPOINT }}
           CORELLIUM_API_TOKEN: ${{ secrets.CORELLIUM_API_TOKEN }}
         run: |
           set -eu && source ./src/functions.sh
-          install_corellium_cafe_ios "${{ env.MATRIX_INSTANCE_ID }}"
+          install_corellium_cafe_android "${{ env.MATRIX_INSTANCE_ID }}"
       - name: Run Corellium Cafe MATRIX assessment
         timeout-minutes: 40
         env:
