fix refactored code

diff --git a/.github/workflows/scan_with_matrix.yaml b/.github/workflows/scan_with_matrix.yaml
--- a/.github/workflows/scan_with_matrix.yaml
+++ b/.github/workflows/scan_with_matrix.yaml
@@ -143,10 +143,9 @@ jobs:
               break
             elif [ "${failures}" -lt "${MAX_MATRIX_RUN_RETRIES}" ]; then
               echo "[!] Warning - MATRIX failed on run $((failures + 1))"
-             else 
-                echo "[!] Error - MATRIX failed the max $((failures + 1)) times" >&2
-                exit 1
-              fi
+            else 
+              echo "[!] Error - MATRIX failed the max $((failures + 1)) times" >&2
+              exit 1
             fi
           done
       - name: Clean up VPN connection
